acme_account:
    resource: "@AcmeAccountBundle/Controller/"
    type:     annotation
    prefix:   /

acme_bundle_blog:
    resource: "@AcmeBundleBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

blog_list:
   path: /jkl
   defaults: { _controller: AcmeAccountBundle:Blog:list }

blog_show:
   path: /jkl/show/{id}
   defaults: { _controller: AcmeAccountBundle:Blog:show }
